export enum EvidenceKind {
  AUTOMATED_TEST = 'AUTOMATED_TEST',
  STATIC_ANALYSIS = 'STATIC_ANALYSIS',
  MANUAL_CHECK = 'MANUAL_CHECK',
  BENCHMARK = 'BENCHMARK',
  STAGING_OBSERVATION = 'STAGING_OBSERVATION',
}
