export enum ReadinessProblem {
  MISSING_INTENT = 'MISSING_INTENT',
  MIXED_PRIMARY_INTENTS = 'MIXED_PRIMARY_INTENTS',
  MISSING_VERIFICATION_EVIDENCE = 'MISSING_VERIFICATION_EVIDENCE',
  BUILD_NOT_INDEPENDENTLY_GREEN = 'BUILD_NOT_INDEPENDENTLY_GREEN',
}
