export enum Eligibility {
  MISSING_CANDIDATE = 'MISSING_CANDIDATE',
  INVALID_RELEASE_ID = 'INVALID_RELEASE_ID',
  NOT_APPROVED = 'NOT_APPROVED',
  TESTS_FAILED = 'TESTS_FAILED',
  WINDOW_CLOSED = 'WINDOW_CLOSED',
  ELIGIBLE = 'ELIGIBLE',
}
